-- PhotoMaker Model Insert Statement
-- Runware PhotoMaker - Advanced image personalization with subject fidelity

INSERT INTO models (
  id,
  name,
  slug,
  type,
  status,
  is_public,
  providers,
  arena_score,
  release_date,
  description,
  examples,
  capabilities,
  apply_image_fn,
  apply_mask_fn,
  apply_quality_fn,
  post_calc_price_fn,
  validate_params_fn,
  tags,
  category,
  max_requests_per_day,
  requires_whitelist,
  created_at,
  updated_at,
  deprecated_at
) VALUES (
  'runware/photomaker',
  'PhotoMaker',
  'photomaker',
  'image',
  'active',
  1,
  '[{"id":"runware","model_name":"photoMaker","pricing":{"type":"calculated","value":0.0013},"maxRetries":3,"timeoutSeconds":120,"requiresAuth":true}]',
  NULL,
  '2024-12-01',
  'Instant subject personalization technology that maintains subject fidelity while applying various styles. Upload up to 4 reference images to generate new images that preserve identity across different scenes and compositions. Supports 11 artistic styles with precise control over transformation strength.',
  '[{"prompt":"rwre wearing a professional suit, corporate headshot","parameters":{"inputImages":["uuid-1","uuid-2","uuid-3"],"style":"Photographic","strength":15,"width":1024,"height":1024}}]',
  '{"supportsImage":true,"supportsMask":false,"supportsQuality":true,"aspectRatios":["1:1","16:9","9:16","4:3","3:4"],"maxResolution":"2048x2048","minResolution":"128x128","defaultResolution":"1024x1024","supportsTextToImage":true,"supportsImageToImage":true,"supportsNegativePrompt":true,"requiresSDXL":true,"maxInputImages":4,"minInputImages":1,"stepsRange":{"min":1,"max":100,"default":20},"guidanceRange":{"min":0,"max":50,"default":7},"strengthRange":{"min":15,"max":50,"default":15},"supportedStyles":["No style","Cinematic","Disney Character","Digital Art","Photographic","Fantasy art","Neonpunk","Enhance","Comic book","Lowpoly","Line art"],"triggerWord":"rwre","clipSkipRange":{"min":0,"max":2},"seedRange":{"min":1,"max":9223372036854776000}}',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '["photomaker","personalization","subject-fidelity","style-transfer","portrait","multi-image","runware","sdxl"]',
  'image-personalization',
  NULL,
  0,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP,
  NULL
)
ON CONFLICT(id) DO UPDATE SET
  name = EXCLUDED.name,
  providers = EXCLUDED.providers,
  capabilities = EXCLUDED.capabilities,
  description = EXCLUDED.description,
  tags = EXCLUDED.tags,
  examples = EXCLUDED.examples,
  updated_at = CURRENT_TIMESTAMP;
